### ISSUE TITLE
@jupyterlab/toc@1.0.1 is not compatible with the current JupyterLab (1.1.4)

### ISSUE THREAD

**Issue by tpanza** [jupyterlab/jupyterlab-toc#104]
Any ideas on how to resolve this?

Running on RHEL 7.6, conda 4.6.3, in a python 3.6 conda env

```shell
$ conda create -y -p /app/local/anaconda3/envs/my-py36 python=3.6
$ source activate my-py36
$ conda install -y numpy=1.16 gast=0.2.2 scipy gensim pandas jupyterlab nodejs
$ jupyter labextension install @jupyterlab/toc --debug
Searching ['/net/ent-home/home/X/XXXXXX', '/net/ent-home/home/X/XXXXXX/.jupyter', '/app/local/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /app/local/anaconda3/etc/jupyter
Looking for jupyter_config in /net/ent-home/home/X/XXXXXX/.jupyter
Looking for jupyter_config in /net/ent-home/home/X/XXXXXX
> /app/local/anaconda3/envs/my-py36/bin/npm pack @jupyterlab/toc
npm notice
npm notice 📦  @jupyterlab/toc@1.0.1
npm notice === Tarball Contents ===
npm notice 2.2kB  package.json
npm notice 1.5kB  LICENSE
npm notice 1.2kB  README.md
npm notice 314B   lib/extension.d.ts
npm notice 3.4kB  lib/extension.js
npm notice 111B   lib/generators/index.d.ts
npm notice 403B   lib/generators/index.js
npm notice 474B   lib/generators/latexgenerator.d.ts
npm notice 2.4kB  lib/generators/latexgenerator.js
npm notice 1.1kB  lib/generators/markdowndocgenerator/index.d.ts
npm notice 7.9kB  lib/generators/markdowndocgenerator/index.js
npm notice 248B   lib/generators/markdowndocgenerator/itemrenderer.d.ts
npm notice 1.0kB  lib/generators/markdowndocgenerator/itemrenderer.js
npm notice 549B   lib/generators/markdowndocgenerator/optionsmanager.d.ts
npm notice 930B   lib/generators/markdowndocgenerator/optionsmanager.js
npm notice 1.2kB  lib/generators/markdowndocgenerator/toolbargenerator.d.ts
npm notice 1.7kB  lib/generators/markdowndocgenerator/toolbargenerator.js
npm notice 546B   lib/generators/notebookgenerator/codemirror.d.ts
npm notice 938B   lib/generators/notebookgenerator/codemirror.js
npm notice 299B   lib/generators/notebookgenerator/heading.d.ts
npm notice 180B   lib/generators/notebookgenerator/heading.js
npm notice 549B   lib/generators/notebookgenerator/index.d.ts
npm notice 18.2kB lib/generators/notebookgenerator/index.js
npm notice 246B   lib/generators/notebookgenerator/itemrenderer.d.ts
npm notice 18.2kB lib/generators/notebookgenerator/index.js                                                                                                                                    [49/254]
npm notice 246B   lib/generators/notebookgenerator/itemrenderer.d.ts
npm notice 5.0kB  lib/generators/notebookgenerator/itemrenderer.js
npm notice 1.2kB  lib/generators/notebookgenerator/optionsmanager.d.ts
npm notice 2.9kB  lib/generators/notebookgenerator/optionsmanager.js
npm notice 1.0kB  lib/generators/notebookgenerator/tagstool/index.d.ts
npm notice 4.7kB  lib/generators/notebookgenerator/tagstool/index.js
npm notice 348B   lib/generators/notebookgenerator/tagstool/tag.d.ts
npm notice 632B   lib/generators/notebookgenerator/tagstool/tag.js
npm notice 574B   lib/generators/notebookgenerator/tagstool/tagslist.d.ts
npm notice 2.1kB  lib/generators/notebookgenerator/tagstool/tagslist.js
npm notice 1.7kB  lib/generators/notebookgenerator/toolbargenerator.d.ts
npm notice 7.7kB  lib/generators/notebookgenerator/toolbargenerator.js
npm notice 1.1kB  lib/generators/shared.d.ts
npm notice 2.6kB  lib/generators/shared.js
npm notice 81B    lib/index.d.ts
npm notice 373B   lib/index.js
npm notice 2.8kB  lib/registry.d.ts
npm notice 1.8kB  lib/registry.js
npm notice 3.6kB  lib/toc.d.ts
npm notice 5.5kB  lib/toc.js
npm notice 559B   style/img/autonumbering_darktheme.svg
npm notice 343B   style/img/autonumbering.svg
npm notice 264B   style/img/check.svg
npm notice 320B   style/img/code_darktheme.svg
npm notice 305B   style/img/code.svg
npm notice 669B   style/img/eyeball_hidden.svg
npm notice 619B   style/img/eyeball_hover.svg
npm notice 617B   style/img/eyeball_view.svg
npm notice 357B   style/img/markdown_darktheme.svg
npm notice 363B   style/img/markdown.svg
npm notice 264B   style/img/menu_arrow.svg
npm notice 523B   style/img/numbering.svg
npm notice 762B   style/img/tag_darktheme.svg
npm notice 1.2kB  style/img/tag.svg
npm notice 202B   style/img/toggle_down_darktheme.svg
npm notice 181B   style/img/toggle_down.svg
npm notice 189B   style/img/toggle_right_darktheme.svg
npm notice 187B   style/img/toggle_right.svg
npm notice 9.3kB  style/index.css
npm notice 625B   style/list-dark.svg
npm notice 625B   style/list-light.svg
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/toc
npm notice version:       1.0.1
npm notice filename:      jupyterlab-toc-1.0.1.tgz
npm notice package size:  24.7 kB
npm notice unpacked size: 111.9 kB
npm notice shasum:        dc2551e628104e66be81fab287e46ea1af272584
npm notice integrity:     sha512-6AQt/7qjNionI[...]hMcGnlF7p+NdQ==
npm notice total files:   64
npm notice integrity:     sha512-6AQt/7qjNionI[...]hMcGnlF7p+NdQ==                                                                                                                              [0/254]
npm notice total files:   64
npm notice
jupyterlab-toc-1.0.1.tgz
Traceback (most recent call last):

  File "/app/local/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 71, in start
    ans = self.run_task()

  File "/app/local/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 100, in run_task
    for arg in self.extra_args

  File "/app/local/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 100, in <listcomp>
    for arg in self.extra_args

  File "/app/local/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 210, in install_extension
    return handler.install_extension(extension)

  File "/app/local/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 347, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/app/local/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1112, in _install_extension
    raise ValueError(msg)

ValueError:
"@jupyterlab/toc@1.0.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/application
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/apputils
>=1.0.6-0 <2.0.0-0      >=3.0.0-0 <4.0.0-0   @jupyterlab/coreutils
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/docmanager
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/fileeditor
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/notebook
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/rendermime



Errored, use --debug for full output:
ValueError:
"@jupyterlab/toc@1.0.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/application
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/apputils
>=1.0.6-0 <2.0.0-0      >=3.0.0-0 <4.0.0-0   @jupyterlab/coreutils
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/docmanager
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/fileeditor
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/notebook
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/rendermime
```

**Comment by kgryte** [comment]
@tpanza Can you try with the latest release candidate?

**Comment by lresende** [comment]
TOC v1.0.1 extension is working ok with latest JupyterLab 1.2.6
