### ISSUE TITLE
ValueError: No version of @jupyterlab/toc could be found that is compatible with the current version of JupyterLab

### ISSUE THREAD

**Issue by slowkow** [jupyterlab/jupyterlab-toc#27]
I tried to update Python to 3.7 and I'm still running into a similar problem to the one described in issue #26.

Here is the complete set of steps I took:

```bash
conda --version
conda 4.5.8

conda create -n py37 jupyterlab python=3.7
source activate py37
conda install -c conda-forge nodejs

jupyter --version
4.4.0

jupyter lab --version
0.32.1

jupyter labextension install @jupyterlab/toc
```

And the result:

```
jupyterlab-toc-0.3.1.tgz

Errored, use --debug for full output:
ValueError: No version of @jupyterlab/toc could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/application
>=0.16.4 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/apputils
>=1.1.3 <2.0.0          >=2.0.0 <3.0.0   @jupyterlab/coreutils
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/docmanager
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/fileeditor
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/notebook
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/rendermime
```

I don't understand how to read the table of conflicting dependencies.

My interpretation goes like this:

- `@jupyterlab/toc` requires `@jupyterlab/application` to be 0.17.0 or newer, but it must be older than 0.18.0

- `@jupyterlab/application` requires jupyterlab to be 0.16.3 or newer, but it must be older than 0.17.0

Is that right? I don't think so, because my jupyterlab is 0.32.1, which is newer than all of the requirements listed in the table.

So, I'm confused and don't understand how to read this or how to debug it any further.

I'd like to ask the following questions:

- What is the correct interpretation of the conflicting dependencies table?

- What steps can I take to work around this issue? Is this a problem with my system? Or is it a bug in the package?

Thanks for any help!

<details>
<summary>jupyter labextension install --debug @jupyterlab/toc</summary>
<pre>

jupyter labextension install --debug @jupyterlab/toc
Searching ['/PHShome/ks38', '/PHShome/ks38/.jupyter', '/data/srlab/slowikow/src/miniconda2/envs/py37/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /data/srlab/slowikow/src/miniconda2/envs/py37/etc/jupyter
Looking for jupyter_config in /PHShome/ks38/.jupyter
Looking for jupyter_config in /PHShome/ks38
> /data/srlab/slowikow/src/miniconda2/envs/py37/bin/npm pack @jupyterlab/toc
npm notice
npm notice 📦  @jupyterlab/toc@0.3.1
npm notice === Tarball Contents ===
npm notice 2.1kB  package.json
npm notice 1.5kB  LICENSE
npm notice 1.2kB  README.md
npm notice 304B   lib/extension.d.ts
npm notice 3.2kB  lib/extension.js
npm notice 1.6kB  lib/generators.d.ts
npm notice 12.4kB lib/generators.js
npm notice 81B    lib/index.d.ts
npm notice 373B   lib/index.js
npm notice 2.1kB  lib/registry.d.ts
npm notice 1.3kB  lib/registry.js
npm notice 3.2kB  lib/toc.d.ts
npm notice 4.9kB  lib/toc.js
npm notice 1.4kB  style/index.css
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/toc
npm notice version:       0.3.1
npm notice filename:      jupyterlab-toc-0.3.1.tgz
npm notice package size:  9.5 kB
npm notice unpacked size: 35.5 kB
npm notice shasum:        0e46f30a3f99174b3e460448968ecc2bc6501496
npm notice integrity:     sha512-nWhBFajzgK5UM[...]EXQK0f7bwxxng==
npm notice total files:   14
npm notice
jupyterlab-toc-0.3.1.tgz
Fetching URL: https://registry.npmjs.org/@jupyterlab%2Ftoc
Fetching URL: https://registry.npmjs.org/@jupyterlab%2Ftoc
Traceback (most recent call last):

  File "/data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 71, in start
    ans = self.run_task()

  File "/data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 100, in run_task
    for arg in self.extra_args

  File "/data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 100, in <listcomp>
    for arg in self.extra_args

  File "/data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/commands.py", line 227, in install_extension
    return handler.install_extension(extension)

  File "/data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/commands.py", line 366, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/commands.py", line 1157, in _install_extension
    raise ValueError(msg)

ValueError: No version of @jupyterlab/toc could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/application
>=0.16.4 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/apputils
>=1.1.3 <2.0.0          >=2.0.0 <3.0.0   @jupyterlab/coreutils
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/docmanager
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/fileeditor
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/notebook
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/rendermime

Errored, use --debug for full output:
ValueError: No version of @jupyterlab/toc could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/application
>=0.16.4 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/apputils
>=1.1.3 <2.0.0          >=2.0.0 <3.0.0   @jupyterlab/coreutils
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/docmanager
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/fileeditor
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/notebook
>=0.16.3 <0.17.0        >=0.17.0 <0.18.0 @jupyterlab/rendermime

</pre>
</details>

**Comment by ian-r-rose** [comment]
Your install of JupyterLab (overall version `0.32`) has a bunch of subpackages. Those are in the `0.16` line, shown in the left column. The *new* version of JupyterLab (in the process of being released) uses the `0.17` line. I released the extension update a few hours early, when the JS subpackages were released but not the overall python package. So `0.3.1` won't work correctly until that release is finalized.

**Comment by ian-r-rose** [comment]
Hi @slowkow, JupyterLab 0.33 has been released, so the most recent version of this should work now. Let me know if you run into any troubles!

**Comment by slowkow** [comment]
Thank you so much for the notification! I didn't expect that it would be ready so soon.

Another bug! This time in nodejs.

Here we go:

```bash
source activate py37
pip install --upgrade pip
pip install --upgrade jupyterlab

jupyter lab --version
0.33.0
```

So far so good. Now let's install the extension:

```bash
jupyter labextension install @jupyterlab/toc
> /data/srlab/slowikow/src/miniconda2/envs/py37/bin/npm pack @jupyterlab/toc
npm notice
npm notice 📦  @jupyterlab/toc@0.3.1
npm notice === Tarball Contents ===
npm notice 2.1kB  package.json
npm notice 1.5kB  LICENSE
npm notice 1.2kB  README.md
npm notice 304B   lib/extension.d.ts
npm notice 3.2kB  lib/extension.js
npm notice 1.6kB  lib/generators.d.ts
npm notice 12.4kB lib/generators.js
npm notice 81B    lib/index.d.ts
npm notice 373B   lib/index.js
npm notice 2.1kB  lib/registry.d.ts
npm notice 1.3kB  lib/registry.js
npm notice 3.2kB  lib/toc.d.ts
npm notice 4.9kB  lib/toc.js
npm notice 1.4kB  style/index.css
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/toc
npm notice version:       0.3.1
npm notice filename:      jupyterlab-toc-0.3.1.tgz
npm notice package size:  9.5 kB
npm notice unpacked size: 35.5 kB
npm notice shasum:        0e46f30a3f99174b3e460448968ecc2bc6501496
npm notice integrity:     sha512-nWhBFajzgK5UM[...]EXQK0f7bwxxng==
npm notice total files:   14
npm notice
jupyterlab-toc-0.3.1.tgz
> node /data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.6.0
(node:20047) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
⠁ @jupyterlab/toc@file:../extensions/jupyterlab-toc-0.3.1.tgz
```

And now it is stuck. The message `Resolving packages...` never finishes, and I have already waited a few minutes.

Seems the same as [this issue][1].

[1]: https://github.com/bokeh/jupyterlab_bokeh/issues/40

The reported solution is to downgrade nodejs from v10 to v9, specifically:

```bash
conda install -c conda-forge nodejs=9.11.1
```

Finally, let's try again:

```bash
jupyter labextension install @jupyterlab/toc
> /data/srlab/slowikow/src/miniconda2/envs/py37/bin/npm pack @jupyterlab/toc
jupyterlab-toc-0.3.1.tgz
> node /data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 103.16s.
> node /data/srlab/slowikow/src/miniconda2/envs/py37/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.6.0
$ webpack --config webpack.prod.config.js
Hash: ef7f2b0006c46d6fede6
Version: webpack 4.12.2
Time: 35820ms
Built at: 2018-07-26 21:14:06
                                   Asset       Size  Chunks                    Chunk Names
    vendors~main.1a7a8c81d6360fee140e.js    2.9 MiB       4  [emitted]  [big]  vendors~main
    674f50d287a8c48dc19ba404d20fe713.eot    162 KiB          [emitted]
    912ec66d7572ff821749319396470bde.svg    434 KiB          [emitted]  [big]
   fee66e712a8a08eef5805a46892932ad.woff   95.7 KiB          [emitted]
    b06871f281fee6b241d60582ae9369b9.ttf    162 KiB          [emitted]
               0.8655c60128912e3ea900.js    441 KiB       0  [emitted]  [big]
    vendors~vega.0b44f1a8a011558b52f6.js    697 KiB       1  [emitted]  [big]  vendors~vega
            vega.9cff6aa9bc603daa8752.js  156 bytes       2  [emitted]         vega
               3.41f272f8c07719e6ad4f.js   3.59 KiB       3  [emitted]
  af7ae505a9eed503f8b8e6982036873e.woff2   75.4 KiB          [emitted]
            main.3d54275a27e73c2ea8e1.js   21.1 KiB       5  [emitted]         main
           0.8655c60128912e3ea900.js.map   1.27 MiB       0  [emitted]
vendors~vega.0b44f1a8a011558b52f6.js.map   2.76 MiB       1  [emitted]         vendors~vega
        vega.9cff6aa9bc603daa8752.js.map  105 bytes       2  [emitted]         vega
           3.41f272f8c07719e6ad4f.js.map   9.25 KiB       3  [emitted]
vendors~main.1a7a8c81d6360fee140e.js.map   9.76 MiB       4  [emitted]         vendors~main
        main.3d54275a27e73c2ea8e1.js.map   77.8 KiB       5  [emitted]         main
                              index.html   1.53 KiB          [emitted]
Entrypoint main [big] = vendors~main.1a7a8c81d6360fee140e.js vendors~main.1a7a8c81d6360fee140e.js.map main.3d54275a27e73c2ea8e1.js main.3d54275a27e73c2ea8e1.js.map
[0] readable-stream (ignored) 15 bytes {5} [built]
[1] crypto (ignored) 15 bytes {5} [optional] [built]
[2] buffer (ignored) 15 bytes {5} [optional] [built]
[YuTi] (webpack)/buildin/module.js 497 bytes {4} [built]
[4] util (ignored) 15 bytes {5} [built]
[5] vertx (ignored) 15 bytes {5} [optional] [built]
[6] multi whatwg-fetch ./build/index.out.js 40 bytes {5} [built]
[7] fs (ignored) 15 bytes {2} [built]
[8] node-fetch (ignored) 15 bytes {2} [built]
[ANye] ./build/index.out.js 34.5 KiB {5} [built]
[J29t] ./node_modules/vega-util/index.js + 36 modules 15.1 KiB {1} [built]
    |    37 modules
[RnhZ] ./node_modules/moment/locale sync ^\.\/.*$ 2.88 KiB {5} [optional] [built]
[eTbV] ./node_modules/codemirror/mode sync ^\.\/.*\.js$ 2.78 KiB {3} [built]
[etOl] ./node_modules/vega-embed/build/src/embed.js + 913 modules 1.64 MiB {1} [built]
    |    914 modules
[yLpj] (webpack)/buildin/global.js 489 bytes {4} [built]
    + 1310 hidden modules

WARNING in react
  Multiple versions of react found:
    16.2.0 ./~/@jupyterlab/toc/~/react from ./~/@jupyterlab/toc/lib/toc.js
    16.4.1 ./~/react from ./~/@jupyterlab/json-extension/lib/index.js


WARNING in react-dom
  Multiple versions of react-dom found:
    16.2.0 ./~/@jupyterlab/toc/~/react-dom from ./~/@jupyterlab/toc/~/react-dom/index.js
    16.4.1 ./~/react-dom from ./~/@jupyterlab/json-extension/lib/index.js


WARNING in vega-lite
  Multiple versions of vega-lite found:
    2.5.1 ./~/vega-lite/build/src from ./~/vega-lite/build/src/index.js
    2.6.0 ./~/vega-lite/build from ./~/vega-lite/build/src/index.js

Check how you can resolve duplicate packages:
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle


WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  912ec66d7572ff821749319396470bde.svg (434 KiB)
  0.8655c60128912e3ea900.js (441 KiB)
  vendors~vega.0b44f1a8a011558b52f6.js (697 KiB)
  vendors~main.1a7a8c81d6360fee140e.js (2.9 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (2.92 MiB)
      vendors~main.1a7a8c81d6360fee140e.js
      main.3d54275a27e73c2ea8e1.js

Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [KTNU] ./node_modules/html-loader!./templates/partial.html 567 bytes {0} [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
    [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.22 KiB {0} [built]
    [yLpj] (webpack)/buildin/global.js 489 bytes {0} [built]
        + 1 hidden module
Done in 37.99s.

```

Success! It works 🎉

**Comment by jaseuts** [comment]
I tried to install TOC for Jupyter Lab 0.32.1 but encountered this problem
```
(base) D:\Users\jng>jupyter labextension install @jupyterlab/toc
> D:\Users\jng\AppData\Local\Continuum\anaconda3\npm.CMD pack @jupyterlab/toc
npm notice
npm notice package: @jupyterlab/toc@3.0.0
npm notice === Tarball Contents ===
npm notice 1.5kB LICENSE
npm notice 9.3kB style/index.css
npm notice 2.6kB lib/generators/notebook/append_collapsible_heading.js
npm notice 1.4kB lib/generators/notebook/append_heading.js
npm notice 1.4kB lib/generators/notebook/append_markdown_heading.js
npm notice 1.3kB lib/generators/notebook/codemirror.js
npm notice 4.0kB lib/extension.js
npm notice 1.4kB lib/utils/generate_numbering.js
npm notice 1.2kB lib/generators/notebook/get_code_cell_heading.js
npm notice 1.6kB lib/generators/markdown/get_headings.js
npm notice 663B  lib/generators/notebook/get_last_heading_level.js
npm notice 1.3kB lib/generators/notebook/get_markdown_heading.js
npm notice 2.3kB lib/generators/markdown/get_rendered_headings.js
npm notice 2.3kB lib/generators/notebook/get_rendered_html_heading.js
npm notice 180B  lib/utils/headings.js
npm notice 443B  lib/generators/index.js
npm notice 2.9kB lib/generators/latex/index.js
npm notice 4.1kB lib/generators/markdown/index.js
npm notice 6.7kB lib/generators/notebook/index.js
npm notice 4.9kB lib/generators/notebook/tagstool/index.js
npm notice 2.5kB lib/generators/python/index.js
npm notice 377B  lib/index.js
npm notice 675B  lib/utils/is_dom.js
npm notice 1.0kB lib/generators/notebook/is_heading_filtered.js
npm notice 764B  lib/utils/is_markdown.js
npm notice 180B  lib/utils/numbering_dictionary.js
npm notice 1.3kB lib/generators/markdown/options_manager.js
npm notice 4.1kB lib/generators/notebook/options_manager.js
npm notice 2.2kB lib/utils/parse_heading.js
npm notice 1.9kB lib/registry.js
npm notice 1.1kB lib/generators/markdown/render.js
npm notice 4.4kB lib/generators/notebook/render.js
npm notice 561B  lib/generators/python/render.js
npm notice 1.1kB lib/utils/sanitizer_options.js
npm notice 6.7kB lib/generators/notebook/set_collapsed_state.js
npm notice 2.3kB lib/generators/notebook/tagstool/tag_list.js
npm notice 870B  lib/generators/notebook/tagstool/tag.js
npm notice 903B  lib/toc_item.js
npm notice 1.1kB lib/toc_tree.js
npm notice 4.2kB lib/toc.js
npm notice 2.1kB lib/generators/markdown/toolbar_generator.js
npm notice 7.9kB lib/generators/notebook/toolbar_generator.js
npm notice 1.3kB lib/generators/notebook/twist_button.js
npm notice 2.1kB package.json
npm notice 1.5kB README.md
npm notice 559B  style/img/autonumbering_darktheme.svg
npm notice 343B  style/img/autonumbering.svg
npm notice 264B  style/img/check.svg
npm notice 320B  style/img/code_darktheme.svg
npm notice 305B  style/img/code.svg
npm notice 669B  style/img/eyeball_hidden.svg
npm notice 619B  style/img/eyeball_hover.svg
npm notice 617B  style/img/eyeball_view.svg
npm notice 625B  style/list-dark.svg
npm notice 625B  style/list-light.svg
npm notice 357B  style/img/markdown_darktheme.svg
npm notice 363B  style/img/markdown.svg
npm notice 264B  style/img/menu_arrow.svg
npm notice 523B  style/img/numbering.svg
npm notice 762B  style/img/tag_darktheme.svg
npm notice 1.2kB style/img/tag.svg
npm notice 202B  style/img/toggle_down_darktheme.svg
npm notice 181B  style/img/toggle_down.svg
npm notice 189B  style/img/toggle_right_darktheme.svg
npm notice 187B  style/img/toggle_right.svg
npm notice 732B  lib/generators/notebook/append_collapsible_heading.d.ts
npm notice 598B  lib/generators/notebook/append_heading.d.ts
npm notice 836B  lib/generators/notebook/append_markdown_heading.d.ts
npm notice 1.2kB lib/generators/notebook/codemirror.d.ts
npm notice 338B  lib/extension.d.ts
npm notice 425B  lib/utils/generate_numbering.d.ts
npm notice 794B  lib/generators/notebook/get_code_cell_heading.d.ts
npm notice 700B  lib/generators/markdown/get_headings.d.ts
npm notice 316B  lib/generators/notebook/get_last_heading_level.d.ts
npm notice 771B  lib/generators/notebook/get_markdown_heading.d.ts
npm notice 698B  lib/generators/markdown/get_rendered_headings.d.ts
npm notice 1.0kB lib/generators/notebook/get_rendered_html_heading.d.ts
npm notice 1.4kB lib/utils/headings.d.ts
npm notice 107B  lib/generators/index.d.ts
npm notice 529B  lib/generators/latex/index.d.ts
npm notice 1.3kB lib/generators/markdown/index.d.ts
npm notice 685B  lib/generators/notebook/index.d.ts
npm notice 2.2kB lib/generators/notebook/tagstool/index.d.ts
npm notice 533B  lib/generators/python/index.d.ts
npm notice 51B   lib/index.d.ts
npm notice 460B  lib/utils/is_dom.d.ts
npm notice 430B  lib/generators/notebook/is_heading_filtered.d.ts
npm notice 466B  lib/utils/is_markdown.d.ts
npm notice 228B  lib/utils/numbering_dictionary.d.ts
npm notice 1.3kB lib/generators/markdown/options_manager.d.ts
npm notice 3.1kB lib/generators/notebook/options_manager.d.ts
npm notice 1.4kB lib/utils/parse_heading.d.ts
npm notice 3.3kB lib/registry.d.ts
npm notice 402B  lib/generators/markdown/render.d.ts
npm notice 530B  lib/generators/notebook/render.d.ts
npm notice 269B  lib/generators/python/render.d.ts
npm notice 469B  lib/utils/sanitizer_options.d.ts
npm notice 572B  lib/generators/notebook/set_collapsed_state.d.ts
npm notice 1.5kB lib/generators/notebook/tagstool/tag_list.d.ts
npm notice 913B  lib/generators/notebook/tagstool/tag.d.ts
npm notice 834B  lib/toc_item.d.ts
npm notice 1.1kB lib/toc_tree.d.ts
npm notice 2.1kB lib/toc.d.ts
npm notice 2.4kB lib/generators/markdown/toolbar_generator.d.ts
npm notice 3.5kB lib/generators/notebook/toolbar_generator.d.ts
npm notice 572B  lib/generators/notebook/twist_button.d.ts
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/toc
npm notice version:       3.0.0
npm notice filename:      jupyterlab-toc-3.0.0.tgz
npm notice package size:  32.7 kB
npm notice unpacked size: 154.9 kB
npm notice shasum:        6457bc1a073addea470ca415f45528685ec22a68
npm notice integrity:     sha512-v2Gs8VSaEdMht[...]xVdZvvQHwvgCg==
npm notice total files:   106
npm notice
jupyterlab-toc-3.0.0.tgz

Errored, use --debug for full output:
ValueError: No version of @jupyterlab/toc could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.3 <0.17.0        >=2.0.0 <3.0.0   @jupyterlab/application
>=0.16.4 <0.17.0        >=2.0.0 <3.0.0   @jupyterlab/apputils
>=1.1.3 <2.0.0          >=4.0.0 <5.0.0   @jupyterlab/coreutils
>=0.16.3 <0.17.0        >=2.0.0 <3.0.0   @jupyterlab/docmanager
>=0.16.3 <0.17.0        >=2.0.0 <3.0.0   @jupyterlab/fileeditor
>=0.16.3 <0.17.0        >=2.0.0 <3.0.0   @jupyterlab/notebook
>=0.16.3 <0.17.0        >=2.0.0 <3.0.0   @jupyterlab/rendermime
```
I believe the requisite for the command `jupyter labextension install @jupyterlab/toc` is JupyterLab >=2.0. The problem is I can't update JupyterLab 0.32.1 to 2.0.1 because of my conda conflicting/inconsistency environment. Is there an archived file where I can install TOC that supports older version of JupyterLab such as 0.32.1?

**Comment by jasongrout** [comment]
According to the published versions on npmjs.com (https://www.npmjs.com/package/@jupyterlab/toc, click "Versions"), the earliest version is 0.3.0, which supports jlab 0.33: https://www.npmjs.com/package/@jupyterlab/toc/v/0.3.0

**Comment by jaseuts** [comment]
Thanks, @jasongrout. However, the commands to install are exactly the same, which is `jupyter labextension install @jupyterlab/toc` for both JupyterLab >=2.0 and JupyterLab v0.33. Consequently, I can't use it to install TOC for my Jupyterlab 0.32 (which is still lower than the minimum requirement Jupyterlab 0.33). Is there a workaround for this?

**Comment by jasongrout** [comment]
> Is there a workaround for this?

It seems that the toc extension was released only for JupyterLab 0.33 or later.

**Comment by jasongrout** [comment]
You could try to take the earliest release of TOC and try to backport it to 0.32, I guess. It is open source, after all. It may be easier to try to upgrade your JupyterLab. 0.32 is almost 2 years old at this point.

**Comment by jaseuts** [comment]
> You could try to take the earliest release of TOC and try to backport it to 0.32, I guess. 

Sorry I'm not a programmer so not sure what you meant by *backport*. Also, where can I find the earliest release of TOC? Thanks

**Comment by jasongrout** [comment]
> Sorry I'm not a programmer so not sure what you meant by _backport_. Also, where can I find the earliest release of TOC?

Someone would have to write a new version of the toc extension that works with jlab 0.32. The earliest release can be found in my [comment](https://github.com/jupyterlab/jupyterlab-toc/issues/27#issuecomment-597074477) earlier: 

> According to the published versions on npmjs.com (https://www.npmjs.com/package/@jupyterlab/toc, click "Versions"), the earliest version is 0.3.0, which supports jlab 0.33: https://www.npmjs.com/package/@jupyterlab/toc/v/0.3.0

**Comment by jasongrout** [comment]
This is the codebase at version 0.3.0: https://github.com/jupyterlab/jupyterlab-toc/tree/v0.3.0

**Comment by jasongrout** [comment]
Interesting, it does look like the codebase has an 0.2 that purports to work in jlab 0.32: https://github.com/jupyterlab/jupyterlab-toc/tree/v0.2.0

Perhaps this was released as https://www.npmjs.com/package/jupyterlab-toc

You could try doing `jupyter labextension install jupyterlab-toc`

**Comment by jaseuts** [comment]
Thanks @jasongrout. I'm amazed that you could find such information (

I followed your instruction by running `jupyter labextension install jupyterlab-toc  ` in anaconda prompt but just got these warning messages and the screen just stayed like that without anything happened. Do you happen to understand those messages and know what's going on? 
```
(base) D:\Users\jng> jupyter labextension install jupyterlab-toc
> D:\Users\jng\AppData\Local\Continuum\anaconda3\npm.CMD pack jupyterlab-toc
npm WARN deprecated jupyterlab-toc@0.2.1: This package has been renamed '@jupyterlab/toc'
npm notice
npm notice package: jupyterlab-toc@0.2.1
npm notice === Tarball Contents ===
npm notice 1.6kB  package.json
npm notice 863B   README.md
npm notice 1.5kB  LICENSE
npm notice 2.9kB  lib/extension.js
npm notice 11.3kB lib/generators.js
npm notice 373B   lib/index.js
npm notice 1.5kB  lib/registry.js
npm notice 6.5kB  lib/toc.js
npm notice 304B   lib/extension.d.ts
npm notice 1.1kB  lib/generators.d.ts
npm notice 81B    lib/index.d.ts
npm notice 2.1kB  lib/registry.d.ts
npm notice 3.2kB  lib/toc.d.ts
npm notice 2.1kB  style/index.css
npm notice === Tarball Details ===
npm notice name:          jupyterlab-toc
npm notice version:       0.2.1
npm notice filename:      jupyterlab-toc-0.2.1.tgz
npm notice package size:  9.5 kB
npm notice unpacked size: 35.5 kB
npm notice shasum:        edd570ba1a523e3e2bf5811b9995f9a99e0c4fe4
npm notice integrity:     sha512-toWEuuN9zi3NM[...]qkQRGoDWupk+g==
npm notice total files:   14
npm notice
jupyterlab-toc-0.2.1.tgz
> node D:\Users\jng09\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.5.1
(node:8840) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
warning @jupyterlab/application > @jupyterlab/apputils > react > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @jupyterlab/application > @jupyterlab/coreutils > comment-json > json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
warning @jupyterlab/faq-extension@0.16.3: The JupyterLab FAQ extension is no longer developed and is removed from JupyterLab 1.0.
warning @jupyterlab/json-extension > react-json-tree > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade you
r dependencies to the actual version of core-js@3.
? jupyterlab-toc@file:../extensions/jupyterlab-toc-0.2.1.tgz
```

**Comment by numeric-lee** [comment]
See also https://github.com/jupyterlab/jupyterlab-toc/issues/156
