### ISSUE TITLE
"@jupyterlab/toc" is not a valid npm package ??

### ISSUE THREAD

**Issue by b-gibbs** [jupyterlab/jupyterlab-toc#35]
I had to uninstall this for a minute since the most recent Conda packages clashed with toc's requirements a couple of weeks ago.  I updated conda again today and thought I'd check to see if the dependencies had worked themselves out, but got this error message, instead.

**Comment by generalrandom** [comment]
I had the same error. Solved by installing node.

**Comment by TRM13** [comment]
I just had this happen. I downloaded the ZIP file and followed the instructions for the development install and it now works. Weird how this pops up again. At least we have a work around.

Running on Windows 10 using Anaconda 3.7 64 bit
base) C:\Anaconda3> jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

**Comment by Dragon1573** [comment]
@generalrandom 

I met the same error as @b-gibbs , and have no idea to solve it. I'm using `cnpm` from [Taobao NPM Mirror](https://npm.taobao.org/) instead of the original `npm` because of some Internet connection policy.  Commands responsed as follows: 

```text
(base) C:\Users\legen>node -v
v12.11.1

(base) C:\Users\legen>where node
D:\Program_Files_(x64)\NodeJS\node.exe

(base) C:\Users\legen>where npm
C:\Users\legen\AppData\Roaming\npm\npm
C:\Users\legen\AppData\Roaming\npm\npm.cmd
D:\Program_Files_(x64)\NodeJS\npm
D:\Program_Files_(x64)\NodeJS\npm.cmd

(base) C:\Users\legen>npm -v
6.12.0

(base) C:\Users\legen>jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

(base) C:\Users\legen>jupyter labextension install @jupyterlab/toc
An error occured.
ValueError: "@jupyterlab/toc" is not a valid npm package
See the log file for details:  C:\Users\legen\AppData\Local\Temp\jupyterlab-debug-ie5zfrk4.log
```

I'm new to `NodeJS` and I have no idea how to solve this problem. Could you do me a favour?

**Comment by Dragon1573** [comment]
@generalrandom 

Oh, the contents of the log files are as follows:

```text
Node v12.11.1

> C:\Users\legen\AppData\Roaming\npm\npm.CMD pack @jupyterlab/toc
系统找不到指定的路径。
npm notice 
npm notice package: @jupyterlab/toc@1.0.1
npm notice === Tarball Contents === 
npm notice 2.2kB  package.json                                             
npm notice 1.5kB  LICENSE                                                  
npm notice 1.2kB  README.md                                                
npm notice 314B   lib/extension.d.ts                                       
npm notice 3.4kB  lib/extension.js                                         
npm notice 111B   lib/generators/index.d.ts                                
npm notice 403B   lib/generators/index.js                                  
npm notice 474B   lib/generators/latexgenerator.d.ts                       
npm notice 2.4kB  lib/generators/latexgenerator.js                         
npm notice 1.1kB  lib/generators/markdowndocgenerator/index.d.ts           
npm notice 7.9kB  lib/generators/markdowndocgenerator/index.js             
npm notice 248B   lib/generators/markdowndocgenerator/itemrenderer.d.ts    
npm notice 1.0kB  lib/generators/markdowndocgenerator/itemrenderer.js      
npm notice 549B   lib/generators/markdowndocgenerator/optionsmanager.d.ts  
npm notice 930B   lib/generators/markdowndocgenerator/optionsmanager.js    
npm notice 1.2kB  lib/generators/markdowndocgenerator/toolbargenerator.d.ts
npm notice 1.7kB  lib/generators/markdowndocgenerator/toolbargenerator.js  
npm notice 546B   lib/generators/notebookgenerator/codemirror.d.ts         
npm notice 938B   lib/generators/notebookgenerator/codemirror.js           
npm notice 299B   lib/generators/notebookgenerator/heading.d.ts            
npm notice 180B   lib/generators/notebookgenerator/heading.js              
npm notice 549B   lib/generators/notebookgenerator/index.d.ts              
npm notice 18.2kB lib/generators/notebookgenerator/index.js                
npm notice 246B   lib/generators/notebookgenerator/itemrenderer.d.ts       
npm notice 5.0kB  lib/generators/notebookgenerator/itemrenderer.js         
npm notice 1.2kB  lib/generators/notebookgenerator/optionsmanager.d.ts     
npm notice 2.9kB  lib/generators/notebookgenerator/optionsmanager.js       
npm notice 1.0kB  lib/generators/notebookgenerator/tagstool/index.d.ts     
npm notice 4.7kB  lib/generators/notebookgenerator/tagstool/index.js       
npm notice 348B   lib/generators/notebookgenerator/tagstool/tag.d.ts       
npm notice 632B   lib/generators/notebookgenerator/tagstool/tag.js         
npm notice 574B   lib/generators/notebookgenerator/tagstool/tagslist.d.ts  
npm notice 2.1kB  lib/generators/notebookgenerator/tagstool/tagslist.js    
npm notice 1.7kB  lib/generators/notebookgenerator/toolbargenerator.d.ts   
npm notice 7.7kB  lib/generators/notebookgenerator/toolbargenerator.js     
npm notice 1.1kB  lib/generators/shared.d.ts                               
npm notice 2.6kB  lib/generators/shared.js                                 
npm notice 81B    lib/index.d.ts                                           
npm notice 373B   lib/index.js                                             
npm notice 2.8kB  lib/registry.d.ts                                        
npm notice 1.8kB  lib/registry.js                                          
npm notice 3.6kB  lib/toc.d.ts                                             
npm notice 5.5kB  lib/toc.js                                               
npm notice 559B   style/img/autonumbering_darktheme.svg                    
npm notice 343B   style/img/autonumbering.svg                              
npm notice 264B   style/img/check.svg                                      
npm notice 320B   style/img/code_darktheme.svg                             
npm notice 305B   style/img/code.svg                                       
npm notice 669B   style/img/eyeball_hidden.svg                             
npm notice 619B   style/img/eyeball_hover.svg                              
npm notice 617B   style/img/eyeball_view.svg                               
npm notice 357B   style/img/markdown_darktheme.svg                         
npm notice 363B   style/img/markdown.svg                                   
npm notice 264B   style/img/menu_arrow.svg                                 
npm notice 523B   style/img/numbering.svg                                  
npm notice 762B   style/img/tag_darktheme.svg                              
npm notice 1.2kB  style/img/tag.svg                                        
npm notice 202B   style/img/toggle_down_darktheme.svg                      
npm notice 181B   style/img/toggle_down.svg                                
npm notice 189B   style/img/toggle_right_darktheme.svg                     
npm notice 187B   style/img/toggle_right.svg                               
npm notice 9.3kB  style/index.css                                          
npm notice 625B   style/list-dark.svg                                      
npm notice 625B   style/list-light.svg                                     
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/toc                         
npm notice version:       1.0.1                                   
npm notice filename:      jupyterlab-toc-1.0.1.tgz                
npm notice package size:  24.7 kB                                 
npm notice unpacked size: 111.9 kB                                
npm notice shasum:        dc2551e628104e66be81fab287e46ea1af272584
npm notice integrity:     sha512-6AQt/7qjNionI[...]hMcGnlF7p+NdQ==
npm notice total files:   64                                      
npm notice 
jupyterlab-toc-1.0.1.tgz

Traceback (most recent call last):

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 147, in run_task
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 147, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 525, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1408, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1478, in _extract_package
    raise ValueError(msg % source)

ValueError: "@jupyterlab/toc" is not a valid npm package

Exiting application: jupyter
```

**Comment by glchaos** [comment]
you can try :
`npm config set strict-ssl false`
and than run :
`jupyter labextension install @jupyterlab/toc`
and run:
`jupyter-lab build`

**Comment by Dragon1573** [comment]
> @glchaos 
>
> You can try `npm config set strict-ssl false` and then run `jupyter labextension install @jupyterlab/toc`

I ran in my powershell (conda environment will automatically activate) as you instructed, but it return the same error log ...

```text
Node v14.4.0

Yarn configuration loaded.
> C:\Users\legen\Anaconda3\npm.CMD pack @jupyterlab/toc
系统找不到指定的路径。
系统找不到指定的路径。
npm notice 
npm notice package: @jupyterlab/toc@4.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB LICENSE                                                
npm notice 9.3kB style/index.css                                        
npm notice 2.6kB lib/generators/notebook/append_collapsible_heading.js  
npm notice 1.4kB lib/generators/notebook/append_heading.js              
npm notice 1.4kB lib/generators/notebook/append_markdown_heading.js     
npm notice 1.3kB lib/generators/notebook/codemirror.js                  
npm notice 5.4kB lib/extension.js                                       
npm notice 1.4kB lib/utils/generate_numbering.js                        
npm notice 1.2kB lib/generators/notebook/get_code_cell_heading.js       
npm notice 1.6kB lib/generators/markdown/get_headings.js                
npm notice 663B  lib/generators/notebook/get_last_heading_level.js      
npm notice 1.3kB lib/generators/notebook/get_markdown_heading.js        
npm notice 2.3kB lib/generators/markdown/get_rendered_headings.js       
npm notice 2.3kB lib/generators/notebook/get_rendered_html_heading.js   
npm notice 180B  lib/utils/headings.js                                  
npm notice 443B  lib/generators/index.js                                
npm notice 2.9kB lib/generators/latex/index.js                          
npm notice 4.1kB lib/generators/markdown/index.js                       
npm notice 6.9kB lib/generators/notebook/index.js                       
npm notice 4.9kB lib/generators/notebook/tagstool/index.js              
npm notice 2.5kB lib/generators/python/index.js                         
npm notice 377B  lib/index.js                                           
npm notice 675B  lib/utils/is_dom.js                                    
npm notice 1.0kB lib/generators/notebook/is_heading_filtered.js         
npm notice 764B  lib/utils/is_markdown.js                               
npm notice 180B  lib/utils/numbering_dictionary.js                      
npm notice 1.3kB lib/generators/markdown/options_manager.js             
npm notice 4.4kB lib/generators/notebook/options_manager.js             
npm notice 2.2kB lib/utils/parse_heading.js                             
npm notice 1.9kB lib/registry.js                                        
npm notice 1.1kB lib/generators/markdown/render.js                      
npm notice 5.0kB lib/generators/notebook/render.js                      
npm notice 561B  lib/generators/python/render.js                        
npm notice 1.1kB lib/utils/sanitizer_options.js                         
npm notice 6.7kB lib/generators/notebook/set_collapsed_state.js         
npm notice 2.3kB lib/generators/notebook/tagstool/tag_list.js           
npm notice 870B  lib/generators/notebook/tagstool/tag.js                
npm notice 903B  lib/toc_item.js                                        
npm notice 1.1kB lib/toc_tree.js                                        
npm notice 4.2kB lib/toc.js                                             
npm notice 2.1kB lib/generators/markdown/toolbar_generator.js           
npm notice 7.9kB lib/generators/notebook/toolbar_generator.js           
npm notice 1.3kB lib/generators/notebook/twist_button.js                
npm notice 2.2kB package.json                                           
npm notice 376B  schema/plugin.json                                     
npm notice 1.5kB README.md                                              
npm notice 559B  style/img/autonumbering_darktheme.svg                  
npm notice 343B  style/img/autonumbering.svg                            
npm notice 264B  style/img/check.svg                                    
npm notice 320B  style/img/code_darktheme.svg                           
npm notice 305B  style/img/code.svg                                     
npm notice 669B  style/img/eyeball_hidden.svg                           
npm notice 619B  style/img/eyeball_hover.svg                            
npm notice 617B  style/img/eyeball_view.svg                             
npm notice 625B  style/list-dark.svg                                    
npm notice 625B  style/list-light.svg                                   
npm notice 357B  style/img/markdown_darktheme.svg                       
npm notice 363B  style/img/markdown.svg                                 
npm notice 264B  style/img/menu_arrow.svg                               
npm notice 523B  style/img/numbering.svg                                
npm notice 762B  style/img/tag_darktheme.svg                            
npm notice 1.2kB style/img/tag.svg                                      
npm notice 202B  style/img/toggle_down_darktheme.svg                    
npm notice 181B  style/img/toggle_down.svg                              
npm notice 189B  style/img/toggle_right_darktheme.svg                   
npm notice 187B  style/img/toggle_right.svg                             
npm notice 732B  lib/generators/notebook/append_collapsible_heading.d.ts
npm notice 598B  lib/generators/notebook/append_heading.d.ts            
npm notice 836B  lib/generators/notebook/append_markdown_heading.d.ts   
npm notice 1.2kB lib/generators/notebook/codemirror.d.ts                
npm notice 338B  lib/extension.d.ts                                     
npm notice 425B  lib/utils/generate_numbering.d.ts                      
npm notice 794B  lib/generators/notebook/get_code_cell_heading.d.ts     
npm notice 700B  lib/generators/markdown/get_headings.d.ts              
npm notice 316B  lib/generators/notebook/get_last_heading_level.d.ts    
npm notice 771B  lib/generators/notebook/get_markdown_heading.d.ts      
npm notice 698B  lib/generators/markdown/get_rendered_headings.d.ts     
npm notice 1.0kB lib/generators/notebook/get_rendered_html_heading.d.ts 
npm notice 1.4kB lib/utils/headings.d.ts                                
npm notice 107B  lib/generators/index.d.ts                              
npm notice 529B  lib/generators/latex/index.d.ts                        
npm notice 1.3kB lib/generators/markdown/index.d.ts                     
npm notice 788B  lib/generators/notebook/index.d.ts                     
npm notice 2.2kB lib/generators/notebook/tagstool/index.d.ts            
npm notice 533B  lib/generators/python/index.d.ts                       
npm notice 51B   lib/index.d.ts                                         
npm notice 460B  lib/utils/is_dom.d.ts                                  
npm notice 430B  lib/generators/notebook/is_heading_filtered.d.ts       
npm notice 466B  lib/utils/is_markdown.d.ts                             
npm notice 228B  lib/utils/numbering_dictionary.d.ts                    
npm notice 1.3kB lib/generators/markdown/options_manager.d.ts           
npm notice 3.4kB lib/generators/notebook/options_manager.d.ts           
npm notice 1.4kB lib/utils/parse_heading.d.ts                           
npm notice 3.3kB lib/registry.d.ts                                      
npm notice 402B  lib/generators/markdown/render.d.ts                    
npm notice 530B  lib/generators/notebook/render.d.ts                    
npm notice 269B  lib/generators/python/render.d.ts                      
npm notice 469B  lib/utils/sanitizer_options.d.ts                       
npm notice 572B  lib/generators/notebook/set_collapsed_state.d.ts       
npm notice 1.5kB lib/generators/notebook/tagstool/tag_list.d.ts         
npm notice 913B  lib/generators/notebook/tagstool/tag.d.ts              
npm notice 834B  lib/toc_item.d.ts                                      
npm notice 1.1kB lib/toc_tree.d.ts                                      
npm notice 2.1kB lib/toc.d.ts                                           
npm notice 2.4kB lib/generators/markdown/toolbar_generator.d.ts         
npm notice 3.5kB lib/generators/notebook/toolbar_generator.d.ts         
npm notice 572B  lib/generators/notebook/twist_button.d.ts              
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/toc                         
npm notice version:       4.0.0                                   
npm notice filename:      jupyterlab-toc-4.0.0.tgz                
npm notice package size:  33.5 kB                                 
npm notice unpacked size: 158.2 kB                                
npm notice shasum:        9b20370dba5a195165ff0d6f541ffc2191818ee6
npm notice integrity:     sha512-bruRUaFw76G6P[...]BHgE63eddLy7w==
npm notice total files:   107                                     
npm notice 
jupyterlab-toc-4.0.0.tgz

Traceback (most recent call last):

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1499, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1578, in _extract_package
    raise ValueError(msg % source)

ValueError: "@jupyterlab/toc" is not a valid npm package

Exiting application: jupyter
```

Maybe going back to `Jupyter Notebook` is a better choice ...

**Comment by rafael-ferro** [comment]
I was getting this error too with _toc_ and other extensions. When I ran `jupyter labextension install @jupyterlab/toc --debug` I got the error `EACCES: permission denied`. As the output suggested, running `sudo chown -R 1000:1000 "/home/rafael/.npm"` did solve the issue for me.

**Comment by aflag** [comment]
If you're using an older version of jupyterlab you will need to pin the version of this extension. For instance, if you have jupyterlab 1.0, the latest version of this extension is 2.0.0.
