### ISSUE TITLE
Can't install un Ubuntu 18.04

### ISSUE THREAD

**Issue by danimateos** [jupyterlab/jupyterlab-toc#73]
Desired behavior: jupyterlab-toc installs and is usable.
Actual behavior: install fails both from `labextension install` and from source.

Environment: Ubuntu 18.04 x64.
jupyter lab --version: 0.35.3
node --version: v8.10.0
npm --version: 3.5.2

Steps to reproduce:
Try to install jupyterlab-toc on Ubuntu 18.04. node and npm installed from Ubuntu repo (needed aptitude to install npm, since apt would complain about node-gyp).

Then:

```
$ jupyter labextension install @jupyterlab/toc
Node v8.10.0

> /usr/bin/npm pack @jupyterlab/toc
jupyterlab-toc-0.6.0.tgz
Node v8.10.0

> node /home/dani/anaconda3/envs/numerical_methods/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[I 09:29:09.526 LabApp] Saving file at /section-01.ipynb
info There appears to be trouble with your network connection. Retrying...
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/home/dani/anaconda3/envs/numerical_methods/share/jupyter/lab/staging/yarn.js:243:66)
    at new MessageError (/home/dani/anaconda3/envs/numerical_methods/share/jupyter/lab/staging/yarn.js:272:123)
    at Function.<anonymous> (/home/dani/anaconda3/envs/numerical_methods/share/jupyter/lab/staging/yarn.js:51226:15)
...
```

Then, tried from source:
```
$ jlpm install
-everything seems fine-
$ jlpm run build
-everything seems fine-
$ jupyter labextension install .
jupyter labextension install .

Node v8.10.0

> /usr/bin/npm pack /home/dani/repos/numerical_methods/jupyterlab-toc
jupyterlab-toc-0.6.0.tgz
Node v8.10.0

> /usr/bin/npm pack /home/dani/repos/numerical_methods/jupyterlab-toc
jupyterlab-toc-0.6.0.tgz
> node /home/dani/anaconda3/envs/numerical_methods/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/home/dani/anaconda3/envs/numerical_methods/share/jupyter/lab/staging/yarn.js:243:66)
...
```
My connection is fine, is the registry actually down???

**Comment by danimateos** [comment]
Never mind, must have been a temporary issue. It worked fine now.
