### ISSUE TITLE
Installation fails with `shutil.SameFileError`

### ISSUE THREAD

**Issue by deisi** [jupyterlab/jupyterlab-toc#76]
Here is a debug output

```
sudo jupyter labextension install @jupyterlab/toc --debug
Searching ['/home/malte', '/root/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /usr/etc/jupyter
Looking for jupyter_config in /root/.jupyter
Looking for jupyter_config in /home/malte
Node v11.8.0

> /usr/bin/npm pack @jupyterlab/toc
npm notice 
npm notice 📦  @jupyterlab/toc@0.6.0
npm notice === Tarball Contents === 
npm notice 2.1kB  package.json                                             
npm notice 1.5kB  LICENSE                                                  
npm notice 1.2kB  README.md                                                
npm notice 304B   lib/extension.d.ts                                       
npm notice 3.3kB  lib/extension.js                                         
npm notice 111B   lib/generators/index.d.ts                                
npm notice 403B   lib/generators/index.js                                  
npm notice 474B   lib/generators/latexgenerator.d.ts                       
npm notice 2.4kB  lib/generators/latexgenerator.js                         
npm notice 1.0kB  lib/generators/markdowndocgenerator/index.d.ts           
npm notice 8.1kB  lib/generators/markdowndocgenerator/index.js             
npm notice 280B   lib/generators/markdowndocgenerator/itemrenderer.d.ts    
npm notice 1.0kB  lib/generators/markdowndocgenerator/itemrenderer.js      
npm notice 549B   lib/generators/markdowndocgenerator/optionsmanager.d.ts  
npm notice 930B   lib/generators/markdowndocgenerator/optionsmanager.js    
npm notice 1.1kB  lib/generators/markdowndocgenerator/toolbargenerator.d.ts
npm notice 1.7kB  lib/generators/markdowndocgenerator/toolbargenerator.js  
npm notice 546B   lib/generators/notebookgenerator/codemirror.d.ts         
npm notice 938B   lib/generators/notebookgenerator/codemirror.js           
npm notice 300B   lib/generators/notebookgenerator/heading.d.ts            
npm notice 180B   lib/generators/notebookgenerator/heading.js              
npm notice 549B   lib/generators/notebookgenerator/index.d.ts              
npm notice 21.9kB lib/generators/notebookgenerator/index.js                
npm notice 278B   lib/generators/notebookgenerator/itemrenderer.d.ts       
npm notice 5.0kB  lib/generators/notebookgenerator/itemrenderer.js         
npm notice 1.0kB  lib/generators/notebookgenerator/optionsmanager.d.ts     
npm notice 2.6kB  lib/generators/notebookgenerator/optionsmanager.js       
npm notice 941B   lib/generators/notebookgenerator/tagstool/index.d.ts     
npm notice 4.7kB  lib/generators/notebookgenerator/tagstool/index.js       
npm notice 348B   lib/generators/notebookgenerator/tagstool/tag.d.ts       
npm notice 632B   lib/generators/notebookgenerator/tagstool/tag.js         
npm notice 574B   lib/generators/notebookgenerator/tagstool/tagslist.d.ts  
npm notice 2.1kB  lib/generators/notebookgenerator/tagstool/tagslist.js    
npm notice 1.6kB  lib/generators/notebookgenerator/toolbargenerator.d.ts   
npm notice 7.4kB  lib/generators/notebookgenerator/toolbargenerator.js     
npm notice 1.1kB  lib/generators/shared.d.ts                               
npm notice 2.6kB  lib/generators/shared.js                                 
npm notice 81B    lib/index.d.ts                                           
npm notice 373B   lib/index.js                                             
npm notice 2.8kB  lib/registry.d.ts                                        
npm notice 1.8kB  lib/registry.js                                          
npm notice 3.6kB  lib/toc.d.ts                                             
npm notice 5.5kB  lib/toc.js                                               
npm notice 559B   style/img/autonumbering_darktheme.svg                    
npm notice 343B   style/img/autonumbering.svg                              
npm notice 264B   style/img/check.svg                                      
npm notice 320B   style/img/code_darktheme.svg                             
npm notice 305B   style/img/code.svg                                       
npm notice 669B   style/img/eyeball_hidden.svg                             
npm notice 619B   style/img/eyeball_hover.svg                              
npm notice 617B   style/img/eyeball_view.svg                               
npm notice 357B   style/img/markdown_darktheme.svg                         
npm notice 363B   style/img/markdown.svg                                   
npm notice 264B   style/img/menu_arrow.svg                                 
npm notice 523B   style/img/numbering.svg                                  
npm notice 762B   style/img/tag_darktheme.svg                              
npm notice 1.2kB  style/img/tag.svg                                        
npm notice 202B   style/img/toggle_down_darktheme.svg                      
npm notice 181B   style/img/toggle_down.svg                                
npm notice 189B   style/img/toggle_right_darktheme.svg                     
npm notice 187B   style/img/toggle_right.svg                               
npm notice 9.0kB  style/index.css                                          
npm notice 625B   style/list-dark.svg                                      
npm notice 625B   style/list-light.svg                                     
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/toc                         
npm notice version:       0.6.0                                   
npm notice filename:      jupyterlab-toc-0.6.0.tgz                
npm notice package size:  24.5 kB                                 
npm notice unpacked size: 114.2 kB                                
npm notice shasum:        393fe861404fa351ece7c4e326a4ddbd2076a39d
npm notice integrity:     sha512-ATlfAY3MhtUvM[...]Sy+NpN6U+RRWw==
npm notice total files:   64                                      
npm notice 
jupyterlab-toc-0.6.0.tgz
Node v11.8.0

Traceback (most recent call last):

  File "/usr/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 81, in start
    logger=self.log, command=command)

  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 274, in build
    command=command, clean_staging=clean_staging)

  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 446, in build
    clean=clean_staging

  File "/usr/lib/python3.7/site-packages/jupyterlab/commands.py", line 871, in _populate_staging
    shutil.copy(pjoin(HERE, 'staging', fname), target)

  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "/usr/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

shutil.SameFileError: '/usr/lib/python3.7/site-packages/jupyterlab/staging/index.js' and '/usr/lib/python3.7/site-packages/jupyterlab/staging/index.js' are the same file


Errored, use --debug for full output:
shutil.SameFileError: '/usr/lib/python3.7/site-packages/jupyterlab/staging/index.js' and '/usr/lib/python3.7/site-packages/jupyterlab/staging/index.js' are the same file
```

I guess it has something to do with the way I installed jupyter lab, because I use the pacman package manager of arch linux instead of pip. Thats also why I try to install the extension system wide.
Is there any way of getting around this by, e.g. forcing the installer to ignore this? 
I mean from what I understand of the message, the installation is failing because a file that it needs is already there, so why is this failing anyways?

**Comment by deisi** [comment]
Okay, I got around this by using `JUPYTERLAB_DIR` env variable and setting it to some home folder.

**Comment by ian-r-rose** [comment]
Hmm, that's odd. Does this happen for any other lab extensions, or just this one? I generally don't try to do system installs, but it should still work in that setting...

**Comment by deisi** [comment]
I tried: `sudo jupyter labextension install @jupyter-widgets/jupyterlab-manager`
and I get the same error.

**Comment by lukasmichel** [comment]
I also got this error when running `sudo jupyter labextension install @jupyter-widgets/jupyterlab-manager` and `sudo jupyter labextension install jupyter-matplotlib`

**Comment by deisi** [comment]
@lukasmichel are you on arch linux as well?

**Comment by lukasmichel** [comment]
Yes

**Comment by Drvanon** [comment]
Did any one of you solve this already?

**Comment by deisi** [comment]
some what.
https://wiki.archlinux.org/index.php/Jupyter#Installation

I followed this. However at some point I had to deinstall packages and go back and forth but eventually I made it work. I think the solution was:

set env virable for jupyter lab

    export JUPYTERLAB_DIR=$HOME/.local/share/jupyter/lab

And then install extension as user:

    jupyter labextension install @jupyterlab/toc

**Comment by Drvanon** [comment]
Thanks!
